#!/bin/sh
echo Transmitting Video $1 To Host $2

gst-launch-1.0 -vv v4l2src device=$1 ! \
'video/x-raw, format=(string)UYVY, width=(int)1280, height=(int)720, framerate=60/1' ! \
videorate drop-only=true max-rate=30 ! \
videoscale ! 'video/x-raw, width=(int)640, height=(int)360' ! \
videoconvert ! \
vaapih264enc ! 'video/x-h264, framerate=30/1, stream-format=(string)byte-stream, bitrate=(int)950, rate-control=(int)2, profile=(string)main' ! \
rtph264pay config-interval=1 ! udpsink host=$2 port=5801

#h264parse ! rtph264pay config-interval=1 ! udpsink host=$2 port=5801
