#!/bin/sh
gst-launch-1.0 -vv udpsrc port=5801 ! \
"application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96" ! \
rtph264depay ! \
vaapih264dec ! \
xvimagesink -e
#vaapisink -e

#decodebin ! \
#videoconvert ! \
#autovideosink



#videoconvert ! \
#xvimagesink -e
