#!/bin/sh
gst-launch-1.0 -vv udpsrc port=5802 ! \
"application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96" ! \
rtph264depay ! \
queue ! \
vaapih264dec low-latency=true ! \
vaapipostproc ! \
xvimagesink -e
